// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.epfl.psytest.domain;

import ch.epfl.psytest.domain.ExperimentSessionDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExperimentSessionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExperimentSessionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExperimentSessionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ExperimentSessionIntegrationTest: @Transactional;
    
    @Autowired
    private ExperimentSessionDataOnDemand ExperimentSessionIntegrationTest.dod;
    
    @Test
    public void ExperimentSessionIntegrationTest.testCountExperimentSessions() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to initialize correctly", dod.getRandomExperimentSession());
        long count = ch.epfl.psytest.domain.ExperimentSession.countExperimentSessions();
        org.junit.Assert.assertTrue("Counter for 'ExperimentSession' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExperimentSessionIntegrationTest.testFindExperimentSession() {
        ch.epfl.psytest.domain.ExperimentSession obj = dod.getRandomExperimentSession();
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to provide an identifier", id);
        obj = ch.epfl.psytest.domain.ExperimentSession.findExperimentSession(id);
        org.junit.Assert.assertNotNull("Find method for 'ExperimentSession' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ExperimentSession' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ExperimentSessionIntegrationTest.testFindAllExperimentSessions() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to initialize correctly", dod.getRandomExperimentSession());
        long count = ch.epfl.psytest.domain.ExperimentSession.countExperimentSessions();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ExperimentSession', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<ch.epfl.psytest.domain.ExperimentSession> result = ch.epfl.psytest.domain.ExperimentSession.findAllExperimentSessions();
        org.junit.Assert.assertNotNull("Find all method for 'ExperimentSession' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ExperimentSession' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExperimentSessionIntegrationTest.testFindExperimentSessionEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to initialize correctly", dod.getRandomExperimentSession());
        long count = ch.epfl.psytest.domain.ExperimentSession.countExperimentSessions();
        if (count > 20) count = 20;
        java.util.List<ch.epfl.psytest.domain.ExperimentSession> result = ch.epfl.psytest.domain.ExperimentSession.findExperimentSessionEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ExperimentSession' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ExperimentSession' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExperimentSessionIntegrationTest.testFlush() {
        ch.epfl.psytest.domain.ExperimentSession obj = dod.getRandomExperimentSession();
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to provide an identifier", id);
        obj = ch.epfl.psytest.domain.ExperimentSession.findExperimentSession(id);
        org.junit.Assert.assertNotNull("Find method for 'ExperimentSession' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyExperimentSession(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ExperimentSession' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExperimentSessionIntegrationTest.testMerge() {
        ch.epfl.psytest.domain.ExperimentSession obj = dod.getRandomExperimentSession();
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to provide an identifier", id);
        obj = ch.epfl.psytest.domain.ExperimentSession.findExperimentSession(id);
        boolean modified =  dod.modifyExperimentSession(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        ch.epfl.psytest.domain.ExperimentSession merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ExperimentSession' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExperimentSessionIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to initialize correctly", dod.getRandomExperimentSession());
        ch.epfl.psytest.domain.ExperimentSession obj = dod.getNewTransientExperimentSession(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ExperimentSession' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ExperimentSession' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ExperimentSessionIntegrationTest.testRemove() {
        ch.epfl.psytest.domain.ExperimentSession obj = dod.getRandomExperimentSession();
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ExperimentSession' failed to provide an identifier", id);
        obj = ch.epfl.psytest.domain.ExperimentSession.findExperimentSession(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ExperimentSession' with identifier '" + id + "'", ch.epfl.psytest.domain.ExperimentSession.findExperimentSession(id));
    }
    
}
